const INTENTS = Object.freeze({
  GREETING: "GREETING",
  SERVICES: "SERVICES",
  BOOK_APPOINTMENT: "BOOK_APPOINTMENT",
  PROMOTIONS: "PROMOTIONS",
  HUMAN_SUPPORT: "HUMAN_SUPPORT",
  UNKNOWN: "UNKNOWN",
});

module.exports = INTENTS;