const CONVERSATION_STEPS = Object.freeze({
  START: "START",
  SELECT_SERVICE: "SELECT_SERVICE",
  SELECT_BARBER: "SELECT_BARBER",
  SELECT_DATE: "SELECT_DATE",
  SELECT_TIME: "SELECT_TIME",
  CONFIRM_BOOKING: "CONFIRM_BOOKING",
  FINISHED: "FINISHED",
});

module.exports = CONVERSATION_STEPS;